language: python
python:
<<<<<<< HEAD
  - 3.6
install:
  - pip install -q -r requirements-dev.txt
script:
  - flake8
=======
  - 3.7
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov
>>>>>>> upstreams/master
